//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

#define PIN_EECIV_2 F3
#define PIN_EECIV_3 F11
#define PIN_EECIV_4 F13
#define PIN_EECIV_5 F4
#define PIN_EECIV_7 EFI_ADC_12
#define PIN_EECIV_8 EFI_ADC_20
#define PIN_EECIV_10 C7
#define PIN_EECIV_12 D11
#define PIN_EECIV_13 D10
#define PIN_EECIV_14 D9
#define PIN_EECIV_15 F12
#define PIN_EECIV_18 EFI_ADC_8
#define PIN_EECIV_19 C9
#define PIN_EECIV_21 G3
#define PIN_EECIV_22 G5
#define PIN_EECIV_23 EFI_ADC_33
#define PIN_EECIV_24 A6
#define PIN_EECIV_25 EFI_ADC_13
#define PIN_EECIV_28 EFI_ADC_32
#define PIN_EECIV_29 EFI_ADC_0
#define PIN_EECIV_30 F5
#define PIN_EECIV_32 G14
#define PIN_EECIV_35 C6
#define PIN_EECIV_36 B9
#define PIN_EECIV_37 EFI_ADC_5
#define PIN_EECIV_41 G4
#define PIN_EECIV_42 EFI_ADC_19
#define PIN_EECIV_43 EFI_ADC_1
#define PIN_EECIV_44 EFI_ADC_3
#define PIN_EECIV_45 EFI_ADC_10
#define PIN_EECIV_47 EFI_ADC_4
#define PIN_EECIV_50 EFI_ADC_14
#define PIN_EECIV_51 C8
#define PIN_EECIV_54 A8
#define PIN_EECIV_55 G6
#define PIN_EECIV_56 B1
#define PIN_EECIV_58 G7
#define PIN_EECIV_59 G8
#define PIN_PE10 E10
